name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 7    

    - name: Install dependencies
      run: | 
        pnpm install
        cd packages/status-page/
        pnpm run docs:build
        cp _worker.js ./dist/_worker.js

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CF_API_TOKEN}}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        projectName: 'status-page'
        directory: 'packages/status-page/dist'
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}