name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 7    

    - name: Install dependencies
      run: | 
        pnpm install
        cd packages/status-page/
        pnpm run docs:build
        cp _worker.js ./dist/_worker.js
        CF_ACCOUNT_ID="${{ secrets.CF_ACCOUNT_ID }}" npx wrangler pages publish dist --project-name="status-page"